import type { Metadata } from "next";
import { Sofia_Sans } from "next/font/google";
import "./globals.css";
import Nav from "@/content/nav";
import classNames from "classnames";

const sofia = Sofia_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames(sofia.className, 'flex my-10 mx-8 gap-8')}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
