import type { Metadata } from "next";
import "./globals.css";

import classNames from "classnames";
import { Sofia_Sans } from "next/font/google";

import Nav from "@/content/nav";

const sofia = Sofia_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body
          className={classNames(
            sofia.className,
            "min-h-screen flex flex-col md:flex-row items-end md:items-stretch"
          )}
        >
          <Nav />
          {children}
        </body>
    </html>
  );
}
