import type { Metadata } from "next";
import '@/app/globals.css';

import classNames from 'classnames';
import { useTranslations } from 'next-intl';
import { Sofia_Sans } from 'next/font/google';

import { Nav, NewNoteDialog } from '@/content';
import Providers from '@/content/provider';

const sofia = Sofia_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  const t = useTranslations();
  return (
    <html lang={params.lang}>
      <body
        className={classNames(
          sofia.className,
          "min-h-screen flex flex-col md:flex-row items-end md:items-stretch"
        )}
      >
        <Providers>
          <NewNoteDialog lang={params.lang} />
          <Nav
            labels={[t("new"), t("notes"), t("tasks"), t("refresh")]}
            lang={params.lang}
          />
          https://{process.env.NEXT_PUBLIC_VERCEL_URL}/api/notes
          {children}
        </Providers>
      </body>
    </html>
  );
}
